version: "3.3"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  nginx:
    image: openlmis/nginx:${OL_NGINX_VERSION}
    ports:
      - "${OL_HTTP_PORT:-80}:80"
    env_file: settings.env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]

  reference-ui:
    image: olmisng/ri-ui:latest
    env_file: settings.env
    depends_on: [consul]

  requisition:
    image: olmisng/requisition-ri:system-upgrade-2023
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  referencedata:
    image: olmisng/referencedata-ri:system-upgrade-2023
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx7g -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  auth:
    image: openlmis/auth:${OL_AUTH_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  notification:
    image: olmisng/notification-ri:latest
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  fulfillment:
    image: olmisng/fulfillment-ri:system-upgrade-2023
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  cce:
    image: olmisng/cce-ri:latest
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  stockmanagement:
    image: olmisng/stockmanagement-ri:openhim-on-receive-fix
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx12g -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  report:
    image: olmisng/report-ri:latest
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  hapifhir:
    restart: always
    image: openlmis/hapifhir:${OL_HAPIFHIR_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    
  diagnostics:
    image: openlmis/diagnostics:${OL_DIAGNOSTICS_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]

  db:
    image: openlmis/postgres:${OL_POSTGRES_VERSION}
    env_file: settings.env
    ports:
      - "9999:5432"
    networks:
      default:
        aliases:
          - olmis-db
    depends_on: [consul]

  log:
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config

  ftp:
    image: driesva/proftpd
    ports:
      - "${OL_FTP_PORT_21:-21}:21"
      - "${OL_FTP_PORT_20:-20}:20"
    env_file: settings.env
    depends_on: [consul]

  redis:
    image: redis:3.2.12
    depends_on: [consul]

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
